application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
      default: linkerd
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
      default: linkerd
  IMAGE_LINKERD:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_LINKERD
